server:
  port: 8081

# Dónde vive el micro que expone /api/saludos)
backend:
  base-url: http://localhost:8080


spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

supabase:
  url: ${SUPABASE_URL}
  table: saludos_extra
  service-key: ${SUPABASE_SERVICE_KEY}